server:
  port: 8082
spring:
  cloud:
    stream:
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: mqTestDefault # 表示要使用的Exchange名称定义
  rabbitmq:                  # 默认的 mq的配置时候，上述的配置方式，可以支持多个 broker
    host: 192.168.33.13
    username: guest
    password: guest
    virtual-host: /
logging:
  config: classpath:logback-spring.xml
  path: ./log/