server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: mqTestDefault    # 目的，对应 MQ 是 exchange， 生成临时队列
        output:
          destination: mqTestDefault
          contentType: text/plain
          binder: defaultRabbit
        inputOrder:
          destination: mqTestOrder
          group: orderReceiveGroup1     # 具体分组 对应 MQ 是 队列名称 并且持久化队列
        outputOrder:
          destination: mqTestOrder
        #          contentType: text/plain
        inputProductAdd:
          destination: mqTestProduct
          group: addProductHandler      # 拥有 group 默认会持久化队列
        outputProductAdd:
          destination: mqTestProduct
      rabbit:
        bindings:
          inputProductAdd:
            consumer:
              bindingRoutingKey: addProduct.*       # 用来绑定消费者的 routing key
          outputProductAdd:
            producer:
              routing-key-expression: '''addProduct.*'''
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.33.13
                username: guest
                password: guest
                virtual-host: /
#  rabbitmq:                  # 默认的 mq的配置时候，上述的配置方式，可以支持多个 broker
#    host: 192.168.33.13
#    username: guest
#    password: guest
#    virtual-host: dev
logging:
  config: classpath:logback-spring.xml
  path: ./log/